### ISSUE TITLE
Add 'container' option to watch for scroll events

### ISSUE THREAD

**Issue by dfedynich** [cferdinandi/gumshoe#47]
Could you add 'container' option to watch for scroll events of the desired form? We can watch for scroll events only for window object in the current implementation, can't we?

**Comment by cferdinandi** [comment]
Yes, currently you can only watch from scrolling globally within in the window object.

Can you tell me a bit more about the use case here? Is there a need that targeting only a specific element would solve that listening globally and then filtering down doesn't address?

**Comment by dfedynich** [comment]
The use case is simple. I have a modal dialog with a navigation panel and scrollable content inside. I want to watch for scroll events inside it.

![image](https://cloud.githubusercontent.com/assets/7403902/18542221/6bf28bc6-7b32-11e6-8fe4-654d1b3d1804.png)

**Comment by cferdinandi** [comment]
Aha, makes perfect sense. This strikes me as a pretty common/worthwhile use case. I'll add this shortly.

**Comment by cferdinandi** [comment]
Added with v3.2.0 (merging as soon as the tests pass): https://github.com/cferdinandi/gumshoe/pull/48

**Comment by attekei** [comment]
Isn't the implementation in v3.2.0 incomplete, because it just adds scroll/resize tracking for the container element, but doesn't actually track the inner height / scroll position of the container? This is needed if the container has something like `overflow: auto`.

For instance in getCurrentNav, the following code:
```js
// Get current position from top of the document
var position = root.pageYOffset; //scrollTop
```

would become something like this:
```js
// Get current scroll position of the container object
// If the container object isn't set, get the position from top of the document
var position = settings.container ? settings.container.scrollTop : root.pageYOffset;
```

The challenge is that there are some cross-browser issues regarding the `scrollTop` property. Would be probably worth looking at Bootstrap scrollspy source code for how they implement the cross-browser support!

**Comment by cferdinandi** [comment]
Bootstrap uses jQuery =(

That's a good point, though. Hmm... I'll have to give this some thought, but candidly, will not be addressing it anytime soon due to other priorities.

**Comment by attekei** [comment]
Thanks! Didn't realize that Bootstrap isn't vanilla JS. But no problem, having a scrollspy in my app isn't a high priority anymore!

**Comment by matthewmcvickar** [comment]
@cferdinandi Is there any chance you have time to look at this issue? In the mobile version of my design, there is a search box in a fixed header. Unfortunately, inputs in fixed-position elements that get focus on iOS cause the browser to scroll to the top of the page. One workaround for this bug/odd behavior is to make the `<body>` 100% height and then make the content area scrollable within a containing element, rather than the `window` itself scrolling. But then the scroll-spying doesn't work (since the root element isn't being scrolled at all).

**Comment by cferdinandi** [comment]
@matthewmcvickar No intention to implement at any point in the foreseeable future. The methods you use to calculate heights and distances within containers varies from how you grab them off the main document, and it's a level of complexity I don't have the time or inclination to support just yet.

I am open a PR to support this, but don't have the time to support myself.

**Comment by david-treblig** [comment]
jQuery now only looks for window.pageYOffset if the element is Window otherwise always uses the scrollTop attribute. I'll make the PR that should make this ok.

**Comment by cferdinandi** [comment]
Would someone on this thread mind checking if v4.x works as desired for this use case? It was rewritten from the ground up with a totally new approach under-the-hood, but I'm not sure if it works for this.

https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0

**Comment by aurnik** [comment]
@cferdinandi I'm using v5.1.0 and was unable to get this to work for a scrollable container within the page. Appreciate the updates though

**Comment by cferdinandi** [comment]
Looking at the updated source code, there's no way for me to support this without a core rewrite. Give that Smooth Scroll doesn't support container-based scrolling either and I'm not interested in rewriting either of them, I'm going to flag this as `wontfix`.

It's a totally valid thing to want, but unfortunately just not something I want to support. Sorry!

**Comment by spsaucier** [comment]
The big use-case here is for using CSS `scroll-snap`, which requires a containing element with `overflow: auto`.

**Comment by cferdinandi** [comment]
I hear you, but see above
