### ISSUE TITLE
Completely refactor

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/gumshoe#81]
Rewrite with a constructor pattern and tweak to better calculate location on the page

**Comment by david-treblig** [comment]
I'd second that. The particular problem that I faced today: needed a "scoped"  version or a second instance because I had two navs with the same classes that both needed to be updated at the same time (it was basically a cloned element). This problem could also have been avoided if gumshoe was making a check to activate all elements with the same "href" instead of a single one.

**Comment by cferdinandi** [comment]
@david-treblig That's the problem I've trying to solve, primarily. I'll be moving to an instantiation pattern that allows for multiple instances with their own settings and selectors on a single page.

```js
var scrollspy1 = new Gumshoe(...);
var scrollspy2 = new Gumshoe(...);
```

**Comment by david-treblig** [comment]
That's great! I think I could have worked through my problem today with two instances and adding classes.

On the other hand, the particular case I came upon today was that I'm using [this](https://github.com/salsita/jq-clipthru) to adjust the color of my navigation on a darker background and, the way that it works, is to create a duplicated / cloned element and clipping it to be able to "mask" / make appear the other color at the same place. 

By working with that kind of cloned elements, the classes are the same on both navs and they're really identical except one small class that is added by the plugin. My logic working through all the limitations of that use case was to reverse the logic: instead of activating the code on the nav element and looking for sections that are scrolled in view, I'd activate the code on the sections scrolled in view and check for all nav elements with the correct target. That also mitigates the obligation to add "live" events and allow dynamic content to work.

Idk if I'm making myself clear or if I'm just rambling, but to put it simpler : now links check if elements are in view, but in my head, elements in view would activate their corresponding links.

**Comment by strarsis** [comment]
[Intersection Observer API
](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by cferdinandi** [comment]
Sadly, no IE support and no good polyfill option on that one.

**Comment by david-treblig** [comment]
There’s an ie6+ polyfill that seems legitimate... considering the performance gain of intersection observer it could be interesting. Though it’s all your call, don’t mean to pressure ahah :P https://github.com/w3c/IntersectionObserver/blob/master/polyfill/README.md

**Comment by cferdinandi** [comment]
No, that's a fair point. I was initially put off by it's large size, but after minification it's "only" 6kb, which is workable. Thanks for that!

**Comment by cferdinandi** [comment]
v4.x is now live! https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0

No intersection observer, as it actually wasn't a great fit for what the script does. But this is a ground-up rewrite with a much better structure and syntax than before. 

Thanks for the feedback, everyone!
