### ISSUE TITLE
Add support for another markup

### ISSUE THREAD

**Issue by Sir-Genius** [cferdinandi/gumshoe#99]
Hi, Chris! Can you add support for the following HTML structure?
```html
<nav>
  <a class="nav-link" href="#anchor1">Link 1</a>
  <a class="nav-link" href="#anchor2">Link 2</a>
</nav>
```

**Comment by cferdinandi** [comment]
Hi Sergei! I totally understand why you'd want this, but I'm not going to add support for this, for two reasons:

1. It adds extra complexity (and places for things to go wrong) to the script for what feels like an edge case because...
2. Semantically speaking, those navigation links *should* be part of a list.

**Comment by exdeniz** [comment]
>Semantically speaking, those navigation links should be part of a list.

**Comment by martinburger** [comment]
This new feature would be great as, for instance, Bulma does not use lists for its [Navbar](https://bulma.io/documentation/components/navbar/).
